//! # AgentPay Smart Account
//!
//! A Soroban smart account representing an AI agent's wallet, built on
//! OpenZeppelin's `stellar-accounts` framework. It uses context rules to
//! scope authorization per vendor contract, and spending-limit policies
//! to enforce per-period spend caps.
//!
//! ## Architecture
//!
//! - One `ContextRule` per allowed vendor/resource contract
//!   (`ContextRuleType::CallContract`).
//! - A `SpendingLimitPolicy` attached to each rule, enforcing a
//!   max-spend-per-period cap.
//! - An admin entrypoint `apply_policy` installs rules + policies from
//!   a `PolicySpec` generated by the Python policy generator.
//! - Events emitted on every authorization decision for audit.

#![no_std]

pub mod policy_spec;

#[cfg(test)]
mod test;

use soroban_sdk::{
    auth::{Context, CustomAccountInterface},
    contract, contracterror, contractimpl, contracttype,
    crypto::Hash,
    Address, BytesN, Env, Map, String, Symbol, Val, Vec,
};
use stellar_accounts::smart_account::{
    self, add_context_rule, do_check_auth, AuthPayload, ContextRule, ContextRuleType, Signer,
    SmartAccount, SmartAccountError,
};

use crate::policy_spec::{AllowedContract, PolicySpec};

// ---------------------------------------------------------------------------
// Storage keys
// ---------------------------------------------------------------------------

#[contracttype]
#[derive(Clone)]
pub enum DataKey {
    /// The admin address that can apply policies.
    Admin,
    /// Tracks the number of rules installed.
    RuleCount,
}

// ---------------------------------------------------------------------------
// Errors
// ---------------------------------------------------------------------------

#[contracterror]
#[derive(Copy, Clone, Debug, PartialEq)]
#[repr(u32)]
pub enum AgentAccountError {
    /// Contract has already been initialized.
    AlreadyInitialized = 1,
    /// Contract has not been initialized.
    NotInitialized = 2,
    /// Caller is not the admin.
    Unauthorized = 3,
    /// PolicySpec contains no allowed contracts.
    EmptyPolicy = 4,
}

// ---------------------------------------------------------------------------
// Contract
// ---------------------------------------------------------------------------

#[contract]
pub struct AgentAccountContract;

#[contractimpl]
impl AgentAccountContract {
    /// Initialize the smart account with an admin address.
    ///
    /// # Arguments
    /// * `admin` - The address that can call `apply_policy` and manage
    ///   the account's authorization rules.
    ///
    /// # Errors
    /// Returns `AlreadyInitialized` if called more than once.
    pub fn initialize(env: Env, admin: Address) -> Result<(), AgentAccountError> {
        if env.storage().instance().has(&DataKey::Admin) {
            return Err(AgentAccountError::AlreadyInitialized);
        }
        env.storage().instance().set(&DataKey::Admin, &admin);
        env.storage().instance().set(&DataKey::RuleCount, &0u32);
        Ok(())
    }

    /// Apply a policy specification generated by the policy generator.
    ///
    /// This installs one `ContextRule` per allowed contract, each scoped
    /// to `ContextRuleType::CallContract(contract_id)`, and attaches a
    /// spending-limit policy to enforce the per-period cap.
    ///
    /// # Arguments
    /// * `admin` - Must match the stored admin; `require_auth` is called.
    /// * `policy_spec` - The `PolicySpec` describing which contracts are
    ///   allowed and their spend limits.
    ///
    /// # Errors
    /// Returns `Unauthorized` if `admin` doesn't match, `EmptyPolicy` if
    /// the spec has no allowed contracts.
    pub fn apply_policy(
        env: Env,
        admin: Address,
        policy_spec: PolicySpec,
    ) -> Result<(), AgentAccountError> {
        // Verify admin
        let stored_admin: Address = env
            .storage()
            .instance()
            .get(&DataKey::Admin)
            .ok_or(AgentAccountError::NotInitialized)?;
        if admin != stored_admin {
            return Err(AgentAccountError::Unauthorized);
        }
        admin.require_auth();

        if policy_spec.allowed_contracts.len() == 0 {
            return Err(AgentAccountError::EmptyPolicy);
        }

        let mut rule_count: u32 = env
            .storage()
            .instance()
            .get(&DataKey::RuleCount)
            .unwrap_or(0u32);

        // Install one context rule per allowed contract
        for i in 0..policy_spec.allowed_contracts.len() {
            let allowed: AllowedContract = policy_spec.allowed_contracts.get(i).unwrap();

            // Build the context rule scoped to this contract
            let context_type = ContextRuleType::CallContract(allowed.contract_id.clone());

            // The signers list: the admin is the sole delegated signer
            let mut signers: Vec<Signer> = Vec::new(&env);
            signers.push_back(Signer::Delegated(admin.clone()));

            // Policies map: keyed by policy contract address → install params
            // TODO: Deploy the SpendingLimitPolicy contract and add it here.
            // For now, we record the spend cap in contract storage directly
            // so the skeleton is functional without a live policy contract.
            let policies: Map<Address, Val> = Map::new(&env);

            let rule_name = String::from_str(
                &env,
                &"agent_rule",
            );

            // Store the rule via the smart account framework
            add_context_rule(
                &env,
                &context_type,
                &rule_name,
                None,
                &signers,
                &policies,
            );
            rule_count += 1;

            // Store the spend cap for this rule in our own storage so
            // `get_remaining_budget` can read it.
            // Key: ("spend_cap", rule_id) → max_spend_per_period
            env.storage().persistent().set(
                &(Symbol::new(&env, "spend_cap"), rule_count),
                &allowed.max_spend_per_period,
            );
            // Store period ledgers
            env.storage().persistent().set(
                &(Symbol::new(&env, "period"), rule_count),
                &policy_spec.period_ledgers,
            );

            // Emit event: policy applied for this contract
            env.events().publish(
                (Symbol::new(&env, "policy_applied"),),
                (allowed.contract_id, allowed.max_spend_per_period),
            );
        }

        env.storage().instance().set(&DataKey::RuleCount, &rule_count);
        Ok(())
    }

    /// Query the remaining spending budget for a given rule.
    ///
    /// # Arguments
    /// * `rule_id` - The context rule ID to check.
    ///
    /// # Returns
    /// The remaining spend allowance in stroops for the current period.
    pub fn get_remaining_budget(env: Env, rule_id: u32) -> i128 {
        let cap: i128 = env
            .storage()
            .persistent()
            .get(&(Symbol::new(&env, "spend_cap"), rule_id))
            .unwrap_or(0);

        let spent: i128 = env
            .storage()
            .persistent()
            .get(&(Symbol::new(&env, "spent"), rule_id))
            .unwrap_or(0);

        // TODO: Implement proper rolling-window spend tracking.
        // For now, simple subtraction.
        cap - spent
    }

    /// Record a spend against a rule's budget. Called internally during
    /// authorization enforcement.
    ///
    /// # Arguments
    /// * `rule_id` - The context rule ID.
    /// * `amount` - The spend amount in stroops.
    ///
    /// # Returns
    /// `true` if the spend was within budget, `false` if denied.
    pub fn record_spend(env: Env, admin: Address, rule_id: u32, amount: i128) -> bool {
        // Only admin can record spends (in production, this would be
        // called by the policy contract during enforcement)
        let stored_admin: Address = env
            .storage()
            .instance()
            .get(&DataKey::Admin)
            .unwrap_or_else(|| panic!("not initialized"));
        if admin != stored_admin {
            env.events().publish(
                (Symbol::new(&env, "auth_decision"),),
                (Symbol::new(&env, "denied"), Symbol::new(&env, "unauthorized")),
            );
            return false;
        }
        admin.require_auth();

        let cap: i128 = env
            .storage()
            .persistent()
            .get(&(Symbol::new(&env, "spend_cap"), rule_id))
            .unwrap_or(0);

        let spent: i128 = env
            .storage()
            .persistent()
            .get(&(Symbol::new(&env, "spent"), rule_id))
            .unwrap_or(0);

        if spent + amount > cap {
            // Denied: over budget
            env.events().publish(
                (Symbol::new(&env, "auth_decision"),),
                (Symbol::new(&env, "denied"), Symbol::new(&env, "over_budget"), amount),
            );
            return false;
        }

        // Approved: record the spend
        env.storage()
            .persistent()
            .set(&(Symbol::new(&env, "spent"), rule_id), &(spent + amount));

        env.events().publish(
            (Symbol::new(&env, "auth_decision"),),
            (Symbol::new(&env, "approved"), amount, spent + amount),
        );

        true
    }

    /// Get the admin address.
    pub fn get_admin(env: Env) -> Result<Address, AgentAccountError> {
        env.storage()
            .instance()
            .get(&DataKey::Admin)
            .ok_or(AgentAccountError::NotInitialized)
    }

    /// Get the total number of context rules installed.
    pub fn get_rule_count(env: Env) -> u32 {
        env.storage()
            .instance()
            .get(&DataKey::RuleCount)
            .unwrap_or(0u32)
    }
}

// ---------------------------------------------------------------------------
// CustomAccountInterface implementation via SmartAccount delegation
// ---------------------------------------------------------------------------

#[contractimpl]
impl CustomAccountInterface for AgentAccountContract {
    type Error = SmartAccountError;
    type Signature = AuthPayload;

    /// Validates authentication and authorization for transactions.
    ///
    /// Delegates to the OpenZeppelin smart account framework's
    /// `do_check_auth`, which handles context rule matching, signer
    /// authentication, and policy enforcement.
    #[allow(non_snake_case)]
    fn __check_auth(
        env: Env,
        signature_payload: Hash<32>,
        signature: AuthPayload,
        auth_contexts: Vec<Context>,
    ) -> Result<(), SmartAccountError> {
        // TODO: Wire up full smart account authorization flow.
        // For now, delegate to the OZ framework's do_check_auth which
        // handles the context-rule matching and policy enforcement.
        do_check_auth(&env, &signature_payload, &signature, &auth_contexts)
    }
}
